# Generated by Django 2.2 on 2021-02-28 09:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAvatar',
            new_name='UserProfile',
        ),
    ]
