# Generated by Django 2.2 on 2021-03-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_auto_20210302_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Аватар'),
        ),
    ]
