# Generated by Django 2.2 on 2020-11-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='comment',
        ),
    ]
