# Generated by Django 2.2 on 2020-11-05 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0002_auto_20201105_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement_type', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='advertisement_status',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='status',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='advertisement_status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_status', to='advertisements_app.Status'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='advertisement_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_type', to='advertisements_app.AdvertisementType'),
        ),
    ]
