# Generated by Django 2.2 on 2020-12-22 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='chef',
            field=models.CharField(max_length=30, verbose_name='Шеф-повар'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='count_of_employers',
            field=models.IntegerField(verbose_name='Кол-во работников'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='country',
            field=models.CharField(max_length=30, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='director',
            field=models.CharField(max_length=30, verbose_name='Директор'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='house',
            field=models.IntegerField(verbose_name='№ дома'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='serves_burgers',
            field=models.BooleanField(default=False, verbose_name='Есть ли бургеры'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='serves_coffee',
            field=models.BooleanField(default=False, verbose_name='Есть ли кофе'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='serves_donats',
            field=models.BooleanField(default=False, verbose_name='Есть ли донаты'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='serves_hot_dogs',
            field=models.BooleanField(default=False, verbose_name='Есть ли хот-доги'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='serves_pizza',
            field=models.BooleanField(default=False, verbose_name='Есть ли пицца'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='serves_sushi',
            field=models.BooleanField(default=False, verbose_name='Есть ли суши'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='street',
            field=models.CharField(max_length=30, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='apartment',
            field=models.IntegerField(verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='country',
            field=models.CharField(max_length=30, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='cources',
            field=models.TextField(max_length=50, verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='education',
            field=models.TextField(max_length=50, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='house',
            field=models.IntegerField(verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant', verbose_name='Ресторан'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='seniority',
            field=models.TextField(verbose_name='Стаж'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='sex',
            field=models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='street',
            field=models.CharField(max_length=30, verbose_name='Улица'),
        ),
    ]
