# Generated by Django 2.2 on 2021-01-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Дополнение пользователя', 'verbose_name_plural': 'Дополнения пользователя'},
        ),
    ]
