# Generated by Django 2.2 on 2021-01-03 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_auto_20201113_1008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_link', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='is_active',
            field=models.BooleanField(default=True, null=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Название'),
        ),
    ]
